### ISSUE TITLE
Issue with southern transects for EC*30to60 meshes

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#218]
I am seeing failures in the following:
* `EC30to60/PHC/files_for_e3sm`
* `ECwISC30to60/PHC/files_for_e3sm`
but these seem unrelated to this PR.  The error message is:
```
 * Running diagnostics_files
     Failed
Traceback (most recent call last):
  File "/home/ac.xylar/chrysalis/miniconda3/envs/fix_ec30to60_dyn/bin/compass", line 33, in <module>
    sys.exit(load_entry_point('compass', 'console_scripts', 'compass')())
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/__main__.py", line 62, in main
    commands[args.command]()
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/run.py", line 272, in main
    run_test_case(args.steps, args.no_steps)
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/run.py", line 226, in run_test_case
    test_case.run()
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/testcase.py", line 166, in run
    self._run_step(step, new_log_file)
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/testcase.py", line 273, in _run_step
    step.run()
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py", line 66, in run
    make_diagnostics_files(self.config, self.logger, mesh_short_name,
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py", line 102, in make_diagnostics_files
    _make_moc_masks(mesh_short_name, logger, cores)
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/fix_ec30to60_dynamical_adjustment/compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py", line 302, in _make_moc_masks
    dsMasksAndTransects = add_moc_southern_boundary_transects(
  File "/home/ac.xylar/chrysalis/miniconda3/envs/fix_ec30to60_dyn/lib/python3.8/site-packages/mpas_tools/ocean/moc.py", line 103, in add_moc_southern_boundary_transects
    _extract_southern_boundary(dsMesh, dsMask, latBuffer=3.*numpy.pi/180.,
  File "/home/ac.xylar/chrysalis/miniconda3/envs/fix_ec30to60_dyn/lib/python3.8/site-packages/mpas_tools/ocean/moc.py", line 179, in _extract_southern_boundary
    _get_edge_sequence_on_boundary(startEdge, edgeSign, edgesOnVertex,
  File "/home/ac.xylar/chrysalis/miniconda3/envs/fix_ec30to60_dyn/lib/python3.8/site-packages/mpas_tools/ocean/moc.py", line 372, in _get_edge_sequence_on_boundary
    assert(nextEdge != -1)
AssertionError
```
I will investigate this separately.

**Comment by xylar** [comment]
This should be fixed as soon as we are able to release a new `mpas_tools` and update the dependency here.
