### ISSUE TITLE
No working gnu or intel config. with SCORPIO

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#39]
Having struggled off and on yesterday and today, I have not been able to get a working MPAS-Ocean build on Grizzly with either gnu or intel and SCORPIO.

## gnu

For gnu, here is the module stack I tried:
```
module purge
module load git
module load friendly-testing
module load gcc/7.4.0 openmpi/2.1.2 hdf5-parallel/1.8.16 pnetcdf/1.11.2 \
    netcdf-h5parallel/4.7.3
...
```
I am able to build SCORPIO successfully.

Then, in debug mode, I get:
```
#0  0x2ad2ea4093ff in ???
#0  0x2ac6e34b83ff in ???
#1  0x8e7fbe in __ocn_time_integration_split_MOD_ocn_time_integration_split_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/core_ocean/mode_forward/mpas_ocn_time_integration_split.F:2272
#1  0x8e7fbe in __ocn_time_integration_split_MOD_ocn_time_integration_split_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/core_ocean/mode_forward/mpas_ocn_time_integration_split.F:2272
#2  0x8e421d in __ocn_forward_mode_MOD_ocn_forward_mode_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/core_ocean/mode_forward/mpas_ocn_forward_mode.F:265
#2  0x8e421d in __ocn_forward_mode_MOD_ocn_forward_mode_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/core_ocean/mode_forward/mpas_ocn_forward_mode.F:265
#3  0xa89389 in __ocn_core_MOD_ocn_core_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/core_ocean/driver/mpas_ocn_core.F:76
#3  0xa89389 in __ocn_core_MOD_ocn_core_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/core_ocean/driver/mpas_ocn_core.F:76
#4  0x40c321 in __mpas_subdriver_MOD_mpas_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/driver/mpas_subdriver.F:331
#4  0x40c321 in __mpas_subdriver_MOD_mpas_init
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/driver/mpas_subdriver.F:331
#5  0x4090af in mpas
#5  0x4090af in mpas
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/driver/mpas.F:14
#6  0x409110 in main
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/driver/mpas.F:10
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/driver/mpas.F:14
#6  0x409110 in main
	at /users/xylar/climate/mpas_work/compass/compass/MPAS-Model/ocean/develop/src/driver/mpas.F:10
```

The error is on a division by zero here:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/mode_forward/mpas_ocn_time_integration_split.F#L2261

It seems to be caused by `layerThickness` being zero everywhere in the halo because there hasn't been a halo update yet.  Thus, the sum of layer thickness is zero as well.

## intel

For intel, I tried the same stack that Phil Wolfram suggested in his build (what is currently in the documentation: https://mpas-dev.github.io/compass/stable/machine_specific_instructions/lanl.html#building-scorpio-on-grizzly)

```
module purge
module load git
module load friendly-testing
module load intel/19.0.4 intel-mpi/2019.4 hdf5-parallel/1.8.16 pnetcdf/1.11.2 \
    netcdf-h5parallel/4.7.3 mkl/2019.0.4
```

To be continued shortly...

**Comment by xylar** [comment]
Moving the gnu issue to MPAS-Model: https://github.com/MPAS-Dev/MPAS-Model/issues/784

**Comment by xylar** [comment]
Moving intel issue to https://github.com/MPAS-Dev/MPAS-Model/issues/785
