### ISSUE TITLE
Error when configuring new env on mac without specifying compiler

### ISSUE THREAD

**Issue by altheaden** [MPAS-Dev/compass#399]
```
Traceback (most recent call last):
  File "/Users/althea/miniconda3/envs/compass_bootstrap/lib/python3.10/configparser.py", line 790, in get
    value = d[option]
  File "/Users/althea/miniconda3/envs/compass_bootstrap/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Users/althea/miniconda3/envs/compass_bootstrap/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'mpi_clang'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/althea/compass/add_parsl/conda/bootstrap.py", line 914, in <module>
    main()
  File "/Users/althea/compass/add_parsl/conda/bootstrap.py", line 789, in main
    compilers, mpis = get_compilers_mpis(config, machine, args.compilers,
  File "/Users/althea/compass/add_parsl/conda/bootstrap.py", line 131, in get_compilers_mpis
    mpi = config.get('deploy', 'mpi_{}'.format(compiler))
  File "/Users/althea/miniconda3/envs/compass_bootstrap/lib/python3.10/configparser.py", line 793, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'mpi_clang' in section: 'deploy'
Traceback (most recent call last):
  File "/Users/althea/compass/add_parsl/./conda/configure_compass_env.py", line 118, in <module>
    main()
  File "/Users/althea/compass/add_parsl/./conda/configure_compass_env.py", line 114, in main
    bootstrap(activate_install_env, source_path, local_conda_build)
  File "/Users/althea/compass/add_parsl/./conda/configure_compass_env.py", line 46, in bootstrap
    check_call(command)
  File "/Users/althea/compass/add_parsl/conda/shared.py", line 144, in check_call
    raise subprocess.CalledProcessError(process.returncode, commands)
subprocess.CalledProcessError: Command 'source /Users/althea/miniconda3/etc/profile.d/conda.sh; conda activate compass_bootstrap; /Users/althea/compass/add_parsl/conda/bootstrap.py --env_name compass_parsl --recreate' returned non-zero exit status 1.
```

**Comment by xylar** [comment]
@hollyhan saw the same issue today.  Unfortunately, I haven't had time to figure it out yet.
