### ISSUE TITLE
`mamba init` fails during compass conda environment setup

### ISSUE THREAD

**Issue by trhille** [MPAS-Dev/compass#544]
On Perlmutter, I get the following error when I execute `./conda/configure_compass_env.py --conda ~/miniconda3 -m pm-cpu --with_albany `:
```
Traceback (most recent call last):
  File "/global/cfs/cdirs/piscees/trhille/compass/./conda/configure_compass_env.py", line 120, in <module>
    main()
  File "/global/cfs/cdirs/piscees/trhille/compass/./conda/configure_compass_env.py", line 102, in main
    install_miniconda(conda_base, activate_base, logger)
  File "/global/cfs/cdirs/piscees/trhille/compass/conda/shared.py", line 181, in install_miniconda
    check_call(commands, logger=logger)
  File "/global/cfs/cdirs/piscees/trhille/compass/conda/shared.py", line 145, in check_call
    raise subprocess.CalledProcessError(process.returncode, commands)
subprocess.CalledProcessError: Command 'source /global/homes/t/trhille/miniconda3/etc/profile.d/conda.sh; source /global/homes/t/trhille/miniconda3/etc/profile.d/mamba.sh; conda activate; conda config --add channels conda-forge; conda config --set channel_priority strict; conda install -y boa; conda update -y --all; mamba init' returned non-zero exit status 1.
```
I tried executing each of the commands in the error, and the issue appears to be the `mamba init` command:
```
'Namespace' object has no attribute 'no_user'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/global/u1/t/<TOKEN>/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/global/u1/t/<TOKEN>/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/global/u1/t/<TOKEN>/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/global/u1/t/<TOKEN>/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/global/u1/t/<TOKEN>/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
        exit_code = shell_init(args)
      File "/global/u1/t/<TOKEN>/mambaforge/lib/python3.10/site-packages/mamba/mamba_shell_init.py", line 87, in shell_init
        if args.no_user:
    AttributeError: 'Namespace' object has no attribute 'no_user'
```
I changed https://github.com/MPAS-Dev/compass/blob/main/conda/shared.py#L179 from `mamba init` to `conda init` and was able to successfully create `dev_compass_1.2.0-alpha.4`

**Comment by trhille** [comment]
I should note that I got the same error when I pointed the `--conda` flag at my mambaforge install.

**Comment by xylar** [comment]
This appears to be an incompatibility between the latest conda and anything but the latest mamba. Something like:
```
source ~/mambaforge/etc/profile.d/conda.sh
source ~/mambaforge/etc/profile.d/mamba.sh
mamba activate
mamba remove -y boa
mamba update mamba
```
should fix it. Then, rerun `./conda/configure...`

**Comment by xylar** [comment]
I can try to add this to compass itself later today.
